<div class="col-xs-12 process">
<div class="col-xs-4 done">Shopping Cart<br><img src="/pub/media/wysiwyg/Basket.png" alt="Shopping Cart"></div>
<div class="col-xs-4 on">Artwork Requirements<br><img src="/pub/media/wysiwyg/Engraving.png" alt="Enter Engraving"></div>
<div class="col-xs-4">Payment<br><img src="/pub/media/wysiwyg/Icon-Payment-Off.png" alt="Enter Payment Details"></div>
</div>
<div class="row">
            <div id="" class="col-xs-12">
            
            <h1 class="text-center text-danger" style="font-weight: bold;">Choose your Artwork Requirements Below</h1>
            &nbsp;
                
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">

            <div id="" class="col-sm-4 text-center select-engraving-btn selectoption1">
			
                <div class="panel1 panel-default">
                    <div class="panel-body">
                        <a href="#">
            <b>Enter Artwork Details Now</b><br>
            Select this option to provide your artwork requirements right now.<br>
                            <span class="text-danger">Perfect For Smaller Orders</span>
                        </a>
                    </div>
                </div>
                
            
		</div>
            <a id="" class="choose-option no-display" href=""><br><br>Choose a different option</a>
            <div id="" class="col-sm-4 text-center select-engraving-btn selectoption2">
			
                <div class="panel1 panel-default">
                    <div class="panel-body">
                        <a id="" href="/checkout/">
            <b>Email Your Artwork Details</b><br>
            You will receive an artwork request email once you have completed your order. Simply reply to this email with your required details within 24 hours.<br>
                            <span class="text-danger">Recommended For Large Orders</span>
                        </a>
                    </div>
                </div>
            
		</div>
            <div id="ctl00_PageContent_SelectOption3Panel" class="col-sm-4 text-center select-engraving-btn selectoption3">
			
                <div class="1 panel-default">
                    <div class="panel-body">
                        <a id="ctl00_PageContent_btnSelectOption3" href="/checkout/">
            <b>No artwork required on your entire order.</b>
                        </a>
                    </div>
                </div>
                <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            
		</div>
        </div>
    </div>
	
<div class="checkout-engraving-details"style="display:none;">

	<?php
	$id = $_GET['pro_id'];
	$quoteId = $_GET['quoteId'];
	foreach($id as $value){
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($value);
 $name =  $product->getName();
    $sku = $product->getSku();
    $shortdesc = $product->getShortDescription();
    $product_id = $product->getId();
	$qty = $product->getQty();
    $image = $product->getImage();
    $type = $product->getTypeId();
    if ($type == 'configurable') {
      $objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
      $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
$productImageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
     // $productImageUrl= 'asd';
    }else{
$prdId = $product_id;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$prdoduct = $objectManager->get('Magento\Catalog\Model\Product')->load($prdId);
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();

$productImageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $prdoduct->getImage();
$productUrl  = $product->getProductUrl();
}?>
<button class="accordion">Enter your engraving details</button>

	<div class="product-info panel">
	<div class="engra-img"><img src="<?php echo $productImageUrl; ?>" width="100px"></div>
	<div class="engra-name">Name: <?php echo $name; ?></div>
	<div class="engra-sku">SKU: <?php echo $sku; ?></div>
	<div class="engra-qty">Quantity:<?php echo $qty; ?></div>
	<div class="col-xs-12 form-horizontal engraving-fields">
                        
						<input type="hidden" name="ctl00$PageContent$EngravingList$ctl00$HiddenCurrentItemNumber" id="ctl00_PageContent_EngravingList_ctl00_HiddenCurrentItemNumber" value="1">
						<div class="engravingitemfirst"><strong>Details for Item: 1</strong><br>
						
	<div class="row"id="clip-items">
	<?php   $product_url=$this->getUrl('*/*/post'); ?>
<form action="<?php echo $product_url; ?>" action="get">


	<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customOptions = $objectManager->get('Magento\Catalog\Model\Product\Option')->getProductOptionCollection($product);

foreach($customOptions as $options){
	//print_r($options->getData());
	  $title = $options['title'];
     $price = $options['price'];
     $sort_order = $options['sort_order'];
	  $option_id = $options['option_id'];
	 $max_characters = $options['max_characters'];

echo '<input type="hidden" name="option_id[]" value="'. $option_id. '">';
?>

<input type="text" id="options_<?php echo $option_id; ?>_text" class="input-text product-custom-option" data-validate="{&quot;maxlength&quot;:&quot;<?php echo $max_characters; ?>&quot;,&quot;validate-no-utf8mb4-characters&quot;:true}" name="options[]" data-selector="options[<?php echo $option_id; ?>]" value="<?php echo $title; ?>" placeholder="<?php echo $title; ?>">

<?php }  ?>
<input type="hidden" name="pro_id" value="<?php echo $product_id; ?>">
<input type="hidden" name="quoteId" value="<?php echo $quoteId; ?>"">

	

	<input type='submit' value='Proceed to next item' class="btn" >
	
</form>
</div>
	</div>
	 
                            
                    </div>
					</div>
	<?php
	}
	?>
	
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

  $addToCartUrl =  $listBlock->getAddToCartUrl($product); ?>

  <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 

    <?php echo $block->getBlockHtml('formkey')?>

     <button type="submit" title="Add to Cart" class="action tocart primary">

       <span>Add to Cart</span>
     </button>
 </form>
</div>
	<script>
	jQuery(".selectoption1").click(function(){
  jQuery(".selectoption2").hide();
   jQuery(".checkout-engraving-details").show();
});
jQuery(".selectoption1").click(function(){
  jQuery(".selectoption3").hide();
});
</script>
	
	<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc; 
}

.panel {
  padding: 0 18px;
  display: none;
  background-color: white;
  overflow: hidden;
}
</style>
<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}
</script>