<?php /* @var $block \SM\Catalogtab\Block\Product\View\Calulcation */ ?>
<?php

ini_set('display_errors', 1);
error_reporting(E_ALL);
$currentProduct = $block->getCurrentProduct();
$shipping_days = $block->getProductAttrValue('shipping_days');
$productId = $currentProduct->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currencyFactory = $objectManager->create('Magento\Directory\Model\CurrencyFactory');
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
$currency = $currencyFactory->create()->load($currencyCode);
$currencySymbol = $currency->getCurrencySymbol();
$fancyStonePrice = '';
$fancyYesNo = $currentProduct->getFancyStone();
if($fancyYesNo == 1){
$sqlFancy = "SELECT * FROM manage_fancystone WHERE  product_id='" . $productId . "'";
$resultFancyStone = $connection->fetchRow($sqlFancy);
$FancyStoneData = unserialize($resultFancyStone['fancystone_data']);
$fancyStonePrice = array_sum($FancyStoneData['price']);
}
$PriceBreakUpYesNo = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('sm_makingcharge/eviayesno/pdp');
$shipDateYesNo = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('sm_makingcharge/eviayesno/expec_ship_date');


?>
<scritp src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></scritp>
<?php if($PriceBreakUpYesNo==1): ?>
<div class="">
    <div class="panel-group" id="accordion">
        <div class="">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <i class="more-less glyphicon glyphicon-plus"></i>
                        View Price Breakup
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    <table class="itemPrichtml">
                        <tbody>
                            <tr>
                                <td><span>Metal</span></td><td rowspan="2">
                                    <img src="http://jewellery.eviaglobal.com/purekarat/skin/frontend/rwd/astra/images/charges-plus.png">
                                </td>
                                <td>
                                    <span>Diamond</span>
                                </td>
                                <td rowspan="2">
                                    <img src="http://jewellery.eviaglobal.com/purekarat/skin/frontend/rwd/astra/images/charges-plus.png">
                                </td>
                                <?php if ($fancyYesNo == 1): ?>
                                    <td>
                                        <span>Stone</span>
                                    </td>
                                    <td rowspan="2">
                                        <img src="http://jewellery.eviaglobal.com/purekarat/skin/frontend/rwd/astra/images/charges-plus.png">
                                    </td>                    
                                <?php endif; ?>                                
                                <td>
                                    <span>Cast Polish Print</span>
                                </td>
                                <td rowspan="2">
                                    <img src="http://jewellery.eviaglobal.com/purekarat/skin/frontend/rwd/astra/images/charges-plus.png">
                                </td>
                                <td>
                                    <span>Set Rate</span>
                                </td>
                                <td rowspan="2">
                                    <img src="http://jewellery.eviaglobal.com/purekarat/skin/frontend/rwd/astra/images/charges-plus.png">
                                </td>
                                <td>
                                    <span>Supplementary Margin</span>
                                </td>
                                <td rowspan="2">
                                    <img src="http://jewellery.eviaglobal.com/purekarat/skin/frontend/rwd/astra/images/charges-plus.png">
                                </td>
                                <td>
                                    <span>Profit Margin</span>
                                </td>
                                <td rowspan="2">
                                    <img src="http://jewellery.eviaglobal.com/purekarat/skin/frontend/rwd/astra/images/charges-plus.png">
                                </td>                                
                                <td><span>Making Charge</span></td>                                
                                <td rowspan="2">
                                    <img src="http://jewellery.eviaglobal.com/purekarat/skin/frontend/rwd/astra/images/charges-plus.png">
                                </td>                                
                                <td><span>VAT</span></td>
                            </tr>
                            <tr class="itemPrichtmlPric">
                                <td id="metalTotalPrice"></td>
                                <td id="diamondTotalPrice"></td>
                                <?php if ($fancyYesNo == 1): ?>
                                    <td id="stoneTotalPrice"></td>
                                <?php endif; ?>                                
                                <td id="castPolishTotalPrice"></td>
                                <td id="setRateTotalPrice"></td>
                                <td id="suppleTotalPrice"></td>
                                <td id="profitTotalPrice"></td>
                                <td id="makingChargeTotal"></td>
                                <td id="vatTotal"></td>
                            </tr>
                        </tbody>
                    </table> 
                </div>
            </div>            
        </div>
    </div><!-- panel-group -->
</div><!-- container -->
<?php endif; ?>
<div class="metalformation clearfix">
    <?php
    $mtOptIds = array();
    $mtOptIds = explode(',', $currentProduct->getMetalType());
    $mtKey = 'metal_type';
    $entityType = 'catalog_product';
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $attributeInfo = $objectManager->create(\Magento\Eav\Model\Entity\Attribute::class)->loadByCode($entityType, $mtKey);
    $mtId = $attributeInfo->getAttributeId();
    $mtData = $objectManager->create(\Magento\Eav\Model\ResourceModel\Entity\Attribute\Option\Collection::class)
            ->setPositionOrder('asc')
            ->setAttributeFilter($mtId)
            ->setStoreFilter()
            ->load();
    $mtOptLabels = array();
    foreach ($mtData as $keyMT => $valMT) {
        //print_r($valMT->getValue());
        $mtOptLabels[$valMT->getOptionId()] = $valMT->getValue();
    }
    $mpOptIds = array();
    $mpOptIds = explode(',', $currentProduct->getMetalPurity());
    $mpAttrKey = 'metal_purity';
    $attributeInfo = $objectManager->create(\Magento\Eav\Model\Entity\Attribute::class)->loadByCode($entityType, $mpAttrKey);
    $mpId = $attributeInfo->getAttributeId();
    $mpData = $objectManager->create(\Magento\Eav\Model\ResourceModel\Entity\Attribute\Option\Collection::class)
            ->setPositionOrder('asc')
            ->setAttributeFilter($mpId)
            ->setStoreFilter()
            ->load();
    $mpOptLabels = array();
    foreach ($mpData as $keyMP => $valMP) {
        $mpOptLabels[$valMP->getOptionId()] = $valMP->getValue();
    }
    $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
    $connection = $resource->getConnection();
    $sql1 = "SELECT * FROM sm_productprice WHERE product_id='" . $productId . "'";
    $result = $connection->fetchAll($sql1);
    $metalDefaultEx = '';
    if(count($result)){
        $metalDefaultEx = explode('x', $result[0]['default_metal']);
    }
    
    $metalDefaultEx[0] = 'dsfsd';
?>
    <div class="metalformation1">
        <label class="metal_label">Metal Selection : </label>
        <select name="metal" id="metal" class="attr">
            <?php foreach ($mtOptIds as $valMT): ?>
                <option value="<?php echo $valMT; ?>" <?php
                if ($metalDefaultEx[0] == $valMT) {
                    echo "selected";
                }
                ?>><?php echo $mtOptLabels[$valMT]; ?></option>
                    <?php endforeach; ?>
        </select>
    </div>

     <div class="metalformation2">
        <div>
            <?php
            $i = 0;
            foreach ($mpOptIds as $valMP):
                ?>
                <input class="attr" type="radio" value="<?php echo $mpOptIds[$i]; ?>" id="purity_<?php echo $mpOptIds[$i]; ?>" name="purity" <?php if ($metalDefaultEx[1] == $valMP) { ?> checked="checked" <?php } ?>>
                <label for="purity_<?php echo $mpOptIds[$i]; ?>"><?php echo $mpOptLabels[$valMP]; ?></label>
                <?php
                $i++;
            endforeach;
            ?>
        </div>
    </div>
    <?php 
    $ccAddedIds = array();
    $ccAddedIds = explode(',', $currentProduct->getDiamondColourClarity());
    $ccKey = 'diamond_colour_clarity';
    $attributeInfo = $objectManager->create(\Magento\Eav\Model\Entity\Attribute::class)->loadByCode($entityType, $ccKey);
    $ccId = $attributeInfo->getAttributeId();
    $ccData = $objectManager->create(\Magento\Eav\Model\ResourceModel\Entity\Attribute\Option\Collection::class)
            ->setPositionOrder('asc')
            ->setAttributeFilter($ccId)
            ->setStoreFilter()
            ->load();
    $ccOptLabelSelected = array();
    foreach ($ccData as $keyCC => $valCC) {
        $ccOptLabelSelected[$valCC->getOptionId()] = $valCC->getValue();
    }
    $attributeSet = $objectManager->create('Magento\Eav\Api\AttributeSetRepositoryInterface');
    $attributeSetRepository = $attributeSet->get($currentProduct->getAttributeSetId());
    $attribute_set_name = $attributeSetRepository->getAttributeSetName();
    $attribute_set_id = $attributeSetRepository->getAttributeSetId();

    $sqlsetName = "SELECT * FROM sm_makingcharge WHERE makingcharge_category='" . $attribute_set_id . "'";
    $resultSetName = $connection->fetchAll($sqlsetName);

//print_r($ccOptLabelSelected);
//echo "<pre>";print_r($resultDiamondColor);
//echo $defaultColorClarity = $resultDiamondColor[0]['color_clarity_id'];
//die;
    ?>   
    <div class="metalformation3">
        <label class="diamond_selection">Diamond Quality : </label>
        <?php
        foreach ($ccAddedIds as $valCC):
            // print_r($valCC);die;
            //print_r($ccOptLabelSelected);
            $sqlDiamondColor = "SELECT * FROM sm_diamond_color_size_data WHERE product_id='" . $productId . "' AND color_clarity_id ='" . $valCC . "' ";
            $resultDiamondColor = $connection->fetchRow($sqlDiamondColor);
            $cnt = count($resultDiamondColor);
            ?>
            <div>            
                <input class="attr" type="radio" value="<?php echo $valCC; ?>" id="diamond_<?php echo $valCC; ?>" name="diamond"
                <?php
                if ($cnt > 0) {
                    $selectedColoCal = $resultDiamondColor['color_clarity_id'];
                    if ($selectedColoCal == $valCC) {
                        ?>checked="checked" <?php
                           }
                       }
                       ?>>
                <label for="diamond_<?php echo $valCC; ?>"><?php echo $ccOptLabelSelected[$valCC]; ?></label>            
            </div>
            <?php
            // }
        endforeach;
        ?>
    </div>
    <?php
    $attributeSet = $objectManager->create('Magento\Eav\Api\AttributeSetRepositoryInterface');
    //$current_product = $objectManager->create('\Magento\Catalog\Model\ProductRepository')->getById($product_id);
    $attributeSetRepository = $attributeSet->get($currentProduct->getAttributeSetId());
    $attribute_set_name = $attributeSetRepository->getAttributeSetName();
    if($attribute_set_name=='Rings'):
    $attributeCode = 'ring_size';
    $entityType = 'catalog_product';
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $attributeInfo = $objectManager->create(\Magento\Eav\Model\Entity\Attribute::class)->loadByCode($entityType, $attributeCode);
    $attributeId = $attributeInfo->getAttributeId();
    $ringSizeIds = explode(',', $currentProduct->getRingSize());
    //echo "<pre>";print_r($ringSizeIds);
//$ds = array();
    $RingSizecnt = count($ringSizeIds);
    for ($i = 0; $i < $RingSizecnt; $i++) {
        $optionId = $ringSizeIds[$i];
        $attributeRigSize = $objectManager->create(\Magento\Eav\Model\ResourceModel\Entity\Attribute\Option\Collection::class)
                ->setPositionOrder('asc')
                ->setAttributeFilter($attributeId)
                ->setIdFilter($optionId)
                ->setStoreFilter()
                ->load();
        if (!empty($attributeRigSize->getData()))
            foreach ($attributeRigSize as $ringSize) {
                $rSize[] = [
                    'value' => $ringSize->getOptionId(),
                    'label' => $ringSize->getValue()
                ];
            }
    }
    
    ?>    
    <div class="metalformation4">
        <label class="diamond_selectiond">Ring Size : </label>
        <div>
            <?php
            $sqlColorSize = "SELECT * FROM sm_diamond_color_size_data WHERE product_id ='" . $currentProduct->getId() . "'";
            $sizeDataCollection = $connection->fetchAll($sqlColorSize);
            ?>            
            <select id="itemSize" name="itemSize" class="attr">
                <?php foreach ($rSize as $ringSizeData): ?>
                    <option value="<?php echo $ringSizeData['value']; ?>" <?php
                    if ($sizeDataCollection[0]['ring_size'] == $ringSizeData['value']) {
                        echo "selected";
                    }
                    ?>><?php echo $ringSizeData['label']; ?></option>
<?php endforeach; ?>
            </select>
        </div>
    </div>
    <?php  endif; ?>
</div>

<?php 
 
    
if($shipping_days!='' && $shipDateYesNo){
    $shipping_days = (int) $shipping_days;
    $date = date("Y-m-d");
    $ship_date =  date('D, F j Y', strtotime($date. ' + '.$shipping_days.' days'));
    
?>
    
<div>
    <span>(Expected shipping date : <?php echo $ship_date; ?>)</span>
</div>
    
<?php } ?>
<input type="hidden" class="attr" name="fancyStonePrice" value="<?php echo $fancyStonePrice; ?>">
<!--<input class="attr" type="hidden" value="1" name="priceFirstCheck" id="priceFirstCheck">-->
<script>
    require(['jquery', 'jqueryBootstrap'], function ($) {
        function toggleIcon(e) {
            $(e.target)
                    .prev('.panel-heading')
                    .find(".more-less")
                    .toggleClass('glyphicon-plus glyphicon-minus');
        }
        $('.panel-group').on('hidden.bs.collapse', toggleIcon);
        $('.panel-group').on('shown.bs.collapse', toggleIcon);
        //$(document).on("change", ".attr", function () {
        //    calculatePrice();
        //});
        $(document).ready(function () {
            var productTotalPrice = $('#metalTotalPrice').html();
            $('.price').val(productTotalPrice);
            setTimeout(calculatePrice, 500);
        });
        var productId = '<?php echo $productId ?>';
        function calculatePrice() {
            $(".loader").show();
            var str = "";
            var str = "productId=" + productId;
            var namelist = new Array();
            $(".attr").each(function (i) {
                var n = $(this).attr("name");
                if (namelist.indexOf(n) == -1) {
                    if (str != "") {
                        str += "&";
                    }
                    if ($(this).attr("type") == "radio") {
                        str += $(this).attr("name") + "=" + $("input[name=" + $(this).attr("name") + "]:checked").val();
                    } else {
                        str += $(this).attr("name") + "=" + $(this).val();
                    }
                    namelist.push($(this).attr("name"));
                }

            });
            var url = '<?php echo $block->getUrl('calculateprice/index/index') ?>' + "?" + str;
            var currencySymbol = '<?php echo $currencySymbol; ?>';
            // console.log(url);
            //var url = calculatepriceUrl+"?"+str;
            $.ajax({
                type: "POST",
                url: url,
                showLoader: true,
                dataType: "JSON",
                success: function (data) {
                    //+ Math.round(data.cashpolish) + Math.round(data.setRateCost) + Math.round(data.supplimentaryPrice) + Math.round(data.profitMargin)
                    //var productPrice = (Math.round(data.metalTotalPrice)  + Math.round(data.diamondTotalPrice) + Math.round(data.fancyStonePrice) + Math.round(data.vatTotal)); //+ Math.round(data.makingChargeTotal)                    
                    var productPrice = (data.finalProductTotal);
                    //var productPrice = (Math.round(data.metalTotalPrice)  + Math.round(data.diamondTotalPrice) + Math.round(data.cashpolish) + Math.round(data.setRateCost) + Math.round(data.supplimentaryPrice) + Math.round(data.profitMargin)); //+ Math.round(data.makingChargeTotal)
                    $('#metalTotalPrice').html(currencySymbol + Math.round(data.metalTotalPrice));
                    $('#makingChargeTotal').html(currencySymbol + Math.round(data.makingChargeTotal));
                    $('#diamondTotalPrice').html(currencySymbol + Math.round(data.diamondTotalPrice));
                    $('#metalWeight').html(data.metalWeight);
                    $('#grossweight').html(data.grossweight);
                    $('#metalType').html(data.metalType);
                    $('#metalPurity').html(data.metalPurity);
	            $('#diamondclarity').html(data.diamondclarity);
		    $('#diamondcolor').html(data.diamondcolor); 
                    $('#castPolishTotalPrice').html(currencySymbol + data.cashpolish); 
                    $('#setRateTotalPrice').html(currencySymbol + data.setRateCost); 
                    $('#suppleTotalPrice').html(currencySymbol + data.supplimentaryPrice); 
                    $('#profitTotalPrice').html(currencySymbol + data.profitMargin); 
                    
                    
                    
                    
                    //$('#priceFirstCheck').val(0);
                  
                    
                    if (data.fancyStonePrice > 0) {
                        $('#stoneTotalPrice').html(Math.round(data.fancyStonePrice));
                    }
                    $('#vatTotal').html(currencySymbol + Math.round(data.vatTotal));
                    $('.price').html(currencySymbol + productPrice);
                    //var productTotalPrice =$('#metalTotalPrice').html(); 
                    //$('.price').val(productTotalPrice);
//				if(jsonReturn.diamondTotalPrice>0){
//				$('#diamondTotalPrice').html(Math.round(jsonReturn.diamondTotalPrice));
//				}

//				if(jsonReturn.fancyStonePrice>0){
//					$('#stonTotalPrice').html(Math.round(jsonReturn.fancyStonePrice));
//				}
//				$('#makingChargeTotal').html(Math.round(jsonReturn.makingChargeTotal));
//				$('#vatTotal').html(Math.round(jsonReturn.vatTotal));
//				$('#metalType').html(jsonReturn.metalType);
//				$('#metalPurity').html(jsonReturn.metalPurity);
//				$('#metalWeight').html(jsonReturn.metalWeight);
//				$('#diamondclarity').html(jsonReturn.diamondclarity);
//				$('#diamondcolor').html(jsonReturn.diamondcolor);
//				$('#grossweight').html(jsonReturn.grossweight);
//				$('#totalCorePriceOff').val(jsonReturn.productTotalCoreCurrencyOff);
//				var productTotalPrice=jsonReturn.productTotal;
//				var productTotalCurrency=jsonReturn.productTotalCurrency;
//				var productTotalCurrencyOff=jsonReturn.productTotalCurrencyOff;
//				$('#totalPrice').val(productTotalPrice);
//				
//				var offerApply=jsonReturn.offerApply;
//				var pid='product-price-'+productId;
//				if(offerApply==1){
//					if(jsonReturn.metalTotalPriceOff>=0){
//						if(jsonReturn.metalTotalPrice!=jsonReturn.metalTotalPriceOff){
//						var metalOff='<del>'+jsonReturn.metalTotalPrice+'</del></br>'+jsonReturn.metalTotalPriceOff;
//							$('#metalTotalPrice').html(metalOff);
//						}
//					}
//					
//					if(jsonReturn.diamondTotalPriceOff>=0){
//						if(jsonReturn.diamondTotalPrice!=jsonReturn.diamondTotalPriceOff){
//						var dimOff='<del>'+jsonReturn.diamondTotalPrice+'</del></br>'+jsonReturn.diamondTotalPriceOff;
//							$('#diamondTotalPrice').html(dimOff);
//						}
//					}
//					
//					if(jsonReturn.fancyStonePriceOff>=0){
//						if(jsonReturn.fancyStonePrice!=jsonReturn.fancyStonePriceOff){
//						var stonOff='<del>'+jsonReturn.fancyStonePrice+'</del></br>'+jsonReturn.fancyStonePriceOff;
//						$('#stonTotalPrice').html(stonOff);
//						}
//						
//					}
//					if(jsonReturn.totalMakingChargeOff>=0){
//						if(jsonReturn.makingChargeTotal!=jsonReturn.totalMakingChargeOff){
//						var makOff='<del>'+jsonReturn.makingChargeTotal+'</del></br>'+jsonReturn.totalMakingChargeOff;
//						$('#makingChargeTotal').html(makOff);
//						}
//						
//					}
//					
//					$('#offerApply').val(offerApply);
//					$('#discountOfferText').val(jsonReturn.discountOfferText);
//					$('#itemAttributeNamePrice').val(jsonReturn.itemAttributeNamePrice);
//					var productTotalPriceOff=jsonReturn.productTotalOff;
//					$('#totalPriceOff').val(productTotalPriceOff);
//					var oldPriceId='old-price-'+productId;
//					$('#'+oldPriceId+'.price').html(productTotalCurrency);	
//					$('#'+pid+'.price').html(productTotalCurrencyOff);
//					$('.offersave-view span').html(parseFloat(productTotalPrice-productTotalPriceOff).toFixed(2));	
//									
//				}else{
//					$('#'+pid+' .price').html(productTotalCurrency);	
//				}
//				

                    //$('#product_addtocart_form .price').html(productTotalCurrency);

                    $(".loader").hide();
                    //console.log(jsonReturn);
                    //alert(jsonReturn.metalTotalPrice);
                }
            });
        }
        ;

//	function checkPinCode(){
//	
//		var getpincode= $('#pincode').val();
//		var splitPin=getpincode.split(',');
//		var pincode= splitPin[0];
//		
//		if(pincode==''){
//		alert('Please Enter Your delivery Pin code!');
//		return false;
//		}else{
//		$(".loader").show();
//		var strPin='pincode='+pincode;
//			var url = pincodeUrl+"?"+strPin;
//			$.ajax({
//				type: "POST",
//				url: url,
//				dataType: "text",
//				success: function(d) {
//					console.log(d);	
//					var splD=d.split('@');
//						var messTx=splD[0];
//						var messStatus=splD[1];	
//						var city=splD[2];
//						var pinWithCity=pincode
//						if(messStatus==1){
//							pinWithCity+=','+city;
//							$('.btn-cart').attr('onclick','productAddToCartForm.submit(this)');
//						}
//						
//						
//					$('#pincode').val(pinWithCity);
//					$("#pincodemessage").html(messTx);
//					$(".loader").hide();
//					
//				}
//			});
//		}
//	}
//	function checkPin(){
//      $('#pincodemessage').html("Please check pincode");
//   } 

    $(document).on("change", "#metal", function () {
        galleryObject = $('[data-gallery-role=gallery-placeholder]').data('gallery');
        var url1 = '<?php echo $block->getUrl('calculateprice/index/images') ?>';
        var text = $("#metal option:selected").text();
        text = text.toLowerCase();
        var productId = '<?php echo $productId ?>';
        $.ajax({
            type: "POST",
            url: url1,
            showLoader: true,
            dataType: "JSON",
            data:{'metal':text,'product':productId},
            success: function (data) {
                galleryObject.updateData(data);
                galleryObject.first();
            }
        });
    });
    
});
    
    
    
</script>
